[defaults]
proton = "system"
prefix_mode = "single"
prefix_path = "~/.local/share/iprolaunch/prefix"
prefixes_root = "~/.local/share/iprolaunch/prefixes"
windows-version = "win10"
gamescope = "none"

[logging]
mode = "single"
path = ""
keep = 3
record = "errors"
auto_open = true

[gamedb]
update_interval_days = 7

[env]

[winedlloverride]

